### ISSUE TITLE
[ERROR] Failed to connect because the specified COM port was not found, exiting...

### ISSUE THREAD

**Issue by nihatxp** [Primoria/Prozac#6]
[ERROR] Failed to connect because the specified COM port was not found, exiting...

**Comment by Primoria** [comment]
ITS LITERALLY SAYING WHAT THE ERROR IS

**Comment by nihatxp** [comment]
> ITS LITERALLY SAYING WHAT THE ERROR IS

I don't know what the com port is, can you help me?
